name: Deploy Digin Site to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Deploy to AWS S3 (production)
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://www.digin.cl

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.DIGIN_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1"
          SOURCE_DIR: clients/digin/site